version: "3.8"
services:
  web:
    image: wordpress:6-php8.1-apache
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html/wp-content/plugins/factpro-for-woocommerce
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: factprouser
      WORDPRESS_DB_PASSWORD: N7MEbMI40m7Z7hIX
      WORDPRESS_DB_NAME: wp-factprodb
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:lts
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=factprouser
      - MYSQL_PASSWORD=N7MEbMI40m7Z7hIX
      - MYSQL_DATABASE=wp-factprodb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
volumes:
  db_data:
